# Generated by Django 4.2.7 on 2023-11-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_otp_code',
            field=models.IntegerField(null=True, verbose_name='Последний OTP-код пользователя'),
        ),
    ]
